COLOR_RED = (0, 0, 255)
SIZE_CARD = (64*3, 89*3)
SIZE_CARD_W, SIZE_CARD_H = SIZE_CARD

PROP_COLOR_RED = 1
PROP_COLOR_GREEN = 2
PROP_COLOR_PURPLE = 3
PROP_COLOR_MAP = ['_', 'RED', 'GREEN', 'PURPLE']

PROP_SHAPE_DIAMOND = 1
PROP_SHAPE_OBLONG = 2
PROP_SHAPE_SQUIGGLE = 3
PROP_SHAPE_MAP = ['_', 'DIAMOND', 'OBLONG', 'SQUIGGLE']

PROP_TEXTURE_STRIPED = 1
PROP_TEXTURE_EMPTY = 2
PROP_TEXTURE_SOLID = 3
PROP_TEXTURE_MAP = ['_', 'STRIPED', 'EMPTY', 'SOLID']
